global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']
        labels:
          service: 'backend'
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']
        labels:
          service: 'gateway'
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications:4002']
        labels:
          service: 'notifications'
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'stock-management'
    static_configs:
      - targets: ['stock-management:4003']
        labels:
          service: 'stock-management'
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']
        labels:
          service: 'mongodb'
